import * as Crypto from "effect/Crypto";
import { Atom } from "effect/unstable/reactivity";

import { createAtomCommandScheduler, createEnvironmentCommand } from "./runtime.ts";
import {
  type ArchiveThreadInput,
  type CreateThreadInput,
  type DeleteThreadInput,
  type InterruptThreadTurnInput,
  type RespondToThreadApprovalInput,
  type RespondToThreadUserInputInput,
  type PublishWayfinderDraftInput,
  type MutateWayfinderInput,
  type ReconcileWayfinderMapInput,
  type ControlWayfinderResearchInput,
  type DismissWorkflowAttachmentHintInput,
  type AttachWorkflowInput,
  type PreflightWorkflowRunInput,
  type ConfirmWorkflowRunInput,
  type StartWorkflowRunInput,
  type PauseWorkflowRunInput,
  type ResumeWorkflowRunInput,
  type HoldWorkflowNodeInput,
  type ReleaseWorkflowNodeInput,
  type ViewWorkflowArtifactsInput,
  type AcknowledgeWorkflowArtifactInput,
  type ResolveWorkflowStaleInput,
  type CompleteWorkflowSpecificationInput,
  type StartWorkflowTicketImplementationInput,
  type StopWorkflowTicketImplementationInput,
  type RecoverWorkflowTicketImplementationInput,
  type RetryWorkflowTicketIntegrationInput,
  type RevertThreadCheckpointInput,
  type SetThreadInteractionModeInput,
  type SetThreadRuntimeModeInput,
  type SettleThreadInput,
  type SnoozeThreadInput,
  type StartThreadTurnInput,
  type StopThreadSessionInput,
  type UnarchiveThreadInput,
  type UnsettleThreadInput,
  type UnsnoozeThreadInput,
  type UpdateThreadMetadataInput,
  archiveThread,
  createThread,
  deleteThread,
  interruptThreadTurn,
  respondToThreadApproval,
  respondToThreadUserInput,
  publishWayfinderDraft,
  mutateWayfinder,
  reconcileWayfinderMap,
  controlWayfinderResearch,
  dismissWorkflowAttachmentHint,
  attachWorkflow,
  preflightWorkflowRun,
  confirmWorkflowRun,
  startWorkflowRun,
  pauseWorkflowRun,
  resumeWorkflowRun,
  holdWorkflowNode,
  releaseWorkflowNode,
  viewWorkflowArtifacts,
  acknowledgeWorkflowArtifact,
  resolveWorkflowStale,
  completeWorkflowSpecification,
  startWorkflowTicketImplementation,
  stopWorkflowTicketImplementation,
  recoverWorkflowTicketImplementation,
  retryWorkflowTicketIntegration,
  revertThreadCheckpoint,
  setThreadInteractionMode,
  setThreadRuntimeMode,
  settleThread,
  snoozeThread,
  startThreadTurn,
  stopThreadSession,
  unarchiveThread,
  unsettleThread,
  unsnoozeThread,
  updateThreadMetadata,
} from "../operations/commands.ts";
import type { EnvironmentRegistry } from "../connection/registry.ts";

export type {
  ArchiveThreadInput,
  CreateThreadInput,
  DeleteThreadInput,
  InterruptThreadTurnInput,
  RespondToThreadApprovalInput,
  RespondToThreadUserInputInput,
  PublishWayfinderDraftInput,
  MutateWayfinderInput,
  ReconcileWayfinderMapInput,
  ControlWayfinderResearchInput,
  DismissWorkflowAttachmentHintInput,
  AttachWorkflowInput,
  PreflightWorkflowRunInput,
  ConfirmWorkflowRunInput,
  StartWorkflowRunInput,
  PauseWorkflowRunInput,
  ResumeWorkflowRunInput,
  HoldWorkflowNodeInput,
  ReleaseWorkflowNodeInput,
  ViewWorkflowArtifactsInput,
  AcknowledgeWorkflowArtifactInput,
  ResolveWorkflowStaleInput,
  CompleteWorkflowSpecificationInput,
  StartWorkflowTicketImplementationInput,
  StopWorkflowTicketImplementationInput,
  RecoverWorkflowTicketImplementationInput,
  RetryWorkflowTicketIntegrationInput,
  RevertThreadCheckpointInput,
  SetThreadInteractionModeInput,
  SetThreadRuntimeModeInput,
  SettleThreadInput,
  SnoozeThreadInput,
  StartThreadTurnInput,
  StopThreadSessionInput,
  UnarchiveThreadInput,
  UnsettleThreadInput,
  UnsnoozeThreadInput,
  UpdateThreadMetadataInput,
} from "../operations/commands.ts";

export function createThreadEnvironmentAtoms<R, E>(
  runtime: Atom.AtomRuntime<EnvironmentRegistry | Crypto.Crypto | R, E>,
) {
  const scheduler = createAtomCommandScheduler();
  const concurrency = {
    mode: "serial" as const,
    key: ({ environmentId, input }: { environmentId: string; input: { threadId: string } }) =>
      JSON.stringify([environmentId, input.threadId]),
  };
  return {
    create: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:create",
      execute: (input: CreateThreadInput) => createThread(input),
      scheduler,
      concurrency,
    }),
    delete: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:delete",
      execute: (input: DeleteThreadInput) => deleteThread(input),
      scheduler,
      concurrency,
    }),
    archive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:archive",
      execute: (input: ArchiveThreadInput) => archiveThread(input),
      scheduler,
      concurrency,
    }),
    unarchive: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unarchive",
      execute: (input: UnarchiveThreadInput) => unarchiveThread(input),
      scheduler,
      concurrency,
    }),
    settle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:settle",
      execute: (input: SettleThreadInput) => settleThread(input),
      scheduler,
      concurrency,
    }),
    unsettle: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsettle",
      execute: (input: UnsettleThreadInput) => unsettleThread(input),
      scheduler,
      concurrency,
    }),
    snooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:snooze",
      execute: (input: SnoozeThreadInput) => snoozeThread(input),
      scheduler,
      concurrency,
    }),
    unsnooze: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:unsnooze",
      execute: (input: UnsnoozeThreadInput) => unsnoozeThread(input),
      scheduler,
      concurrency,
    }),
    updateMetadata: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:update-metadata",
      execute: (input: UpdateThreadMetadataInput) => updateThreadMetadata(input),
      scheduler,
      concurrency,
    }),
    setRuntimeMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-runtime-mode",
      execute: (input: SetThreadRuntimeModeInput) => setThreadRuntimeMode(input),
      scheduler,
      concurrency,
    }),
    setInteractionMode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:set-interaction-mode",
      execute: (input: SetThreadInteractionModeInput) => setThreadInteractionMode(input),
      scheduler,
      concurrency,
    }),
    startTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:start-turn",
      execute: (input: StartThreadTurnInput) => startThreadTurn(input),
      scheduler,
      concurrency,
    }),
    interruptTurn: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:interrupt-turn",
      execute: (input: InterruptThreadTurnInput) => interruptThreadTurn(input),
      scheduler,
      concurrency,
    }),
    respondToApproval: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-approval",
      execute: (input: RespondToThreadApprovalInput) => respondToThreadApproval(input),
      scheduler,
      concurrency,
    }),
    respondToUserInput: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:respond-to-user-input",
      execute: (input: RespondToThreadUserInputInput) => respondToThreadUserInput(input),
      scheduler,
      concurrency,
    }),
    publishWayfinderDraft: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:publish-wayfinder-draft",
      execute: (input: PublishWayfinderDraftInput) => publishWayfinderDraft(input),
      scheduler,
      concurrency,
    }),
    mutateWayfinder: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:mutate-wayfinder",
      execute: (input: MutateWayfinderInput) => mutateWayfinder(input),
      scheduler,
      concurrency,
    }),
    reconcileWayfinderMap: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:reconcile-wayfinder-map",
      execute: (input: ReconcileWayfinderMapInput) => reconcileWayfinderMap(input),
      scheduler,
      concurrency,
    }),
    controlWayfinderResearch: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:control-wayfinder-research",
      execute: (input: ControlWayfinderResearchInput) => controlWayfinderResearch(input),
      scheduler,
      concurrency,
    }),
    dismissWorkflowAttachmentHint: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:dismiss-workflow-attachment-hint",
      execute: (input: DismissWorkflowAttachmentHintInput) => dismissWorkflowAttachmentHint(input),
      scheduler,
      concurrency,
    }),
    attachWorkflow: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:attach-workflow",
      execute: (input: AttachWorkflowInput) => attachWorkflow(input),
      scheduler,
      concurrency,
    }),
    preflightWorkflowRun: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:preflight-workflow-run",
      execute: (input: PreflightWorkflowRunInput) => preflightWorkflowRun(input),
      scheduler,
      concurrency,
    }),
    confirmWorkflowRun: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:confirm-workflow-run",
      execute: (input: ConfirmWorkflowRunInput) => confirmWorkflowRun(input),
      scheduler,
      concurrency,
    }),
    startWorkflowRun: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:start-workflow-run",
      execute: (input: StartWorkflowRunInput) => startWorkflowRun(input),
      scheduler,
      concurrency,
    }),
    pauseWorkflowRun: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:pause-workflow-run",
      execute: (input: PauseWorkflowRunInput) => pauseWorkflowRun(input),
      scheduler,
      concurrency,
    }),
    resumeWorkflowRun: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:resume-workflow-run",
      execute: (input: ResumeWorkflowRunInput) => resumeWorkflowRun(input),
      scheduler,
      concurrency,
    }),
    holdWorkflowNode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:hold-workflow-node",
      execute: (input: HoldWorkflowNodeInput) => holdWorkflowNode(input),
      scheduler,
      concurrency,
    }),
    releaseWorkflowNode: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:release-workflow-node",
      execute: (input: ReleaseWorkflowNodeInput) => releaseWorkflowNode(input),
      scheduler,
      concurrency,
    }),
    viewWorkflowArtifacts: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:view-workflow-artifacts",
      execute: (input: ViewWorkflowArtifactsInput) => viewWorkflowArtifacts(input),
      scheduler,
      concurrency,
    }),
    acknowledgeWorkflowArtifact: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:acknowledge-workflow-artifact",
      execute: (input: AcknowledgeWorkflowArtifactInput) => acknowledgeWorkflowArtifact(input),
      scheduler,
      concurrency,
    }),
    resolveWorkflowStale: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:resolve-workflow-stale",
      execute: (input: ResolveWorkflowStaleInput) => resolveWorkflowStale(input),
      scheduler,
      concurrency,
    }),
    completeWorkflowSpecification: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:complete-workflow-specification",
      execute: (input: CompleteWorkflowSpecificationInput) => completeWorkflowSpecification(input),
      scheduler,
      concurrency,
    }),
    startTicketImplementation: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:start-ticket-implementation",
      execute: (input: StartWorkflowTicketImplementationInput) =>
        startWorkflowTicketImplementation(input),
      scheduler,
      concurrency,
    }),
    stopTicketImplementation: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:stop-ticket-implementation",
      execute: (input: StopWorkflowTicketImplementationInput) =>
        stopWorkflowTicketImplementation(input),
      scheduler,
      concurrency,
    }),
    recoverTicketImplementation: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:recover-ticket-implementation",
      execute: (input: RecoverWorkflowTicketImplementationInput) =>
        recoverWorkflowTicketImplementation(input),
      scheduler,
      concurrency,
    }),
    retryTicketIntegration: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:retry-ticket-integration",
      execute: (input: RetryWorkflowTicketIntegrationInput) =>
        retryWorkflowTicketIntegration(input),
      scheduler,
      concurrency,
    }),
    revertCheckpoint: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:revert-checkpoint",
      execute: (input: RevertThreadCheckpointInput) => revertThreadCheckpoint(input),
      scheduler,
      concurrency,
    }),
    stopSession: createEnvironmentCommand(runtime, {
      label: "environment-data:commands:thread:stop-session",
      execute: (input: StopThreadSessionInput) => stopThreadSession(input),
      scheduler,
      concurrency,
    }),
  };
}
