import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  ThreadWayfinderPublicationUpdatedPayload as ContractsThreadWayfinderPublicationUpdatedPayloadSchema,
  ThreadWayfinderMutationUpdatedPayload as ContractsThreadWayfinderMutationUpdatedPayloadSchema,
  ThreadWayfinderReconciliationUpdatedPayload as ContractsThreadWayfinderReconciliationUpdatedPayloadSchema,
  ThreadWayfinderResearchUpdatedPayload as ContractsThreadWayfinderResearchUpdatedPayloadSchema,
  ThreadWorkflowAttachedPayload as ContractsThreadWorkflowAttachedPayloadSchema,
  ThreadWorkflowRunPreflightedPayload as ContractsThreadWorkflowRunPreflightedPayloadSchema,
  ThreadWorkflowRunConfirmedPayload as ContractsThreadWorkflowRunConfirmedPayloadSchema,
  ThreadWorkflowArtifactAcknowledgedPayload as ContractsThreadWorkflowArtifactAcknowledgedPayloadSchema,
  ThreadWorkflowAttachmentHintDismissedPayload as ContractsThreadWorkflowAttachmentHintDismissedPayloadSchema,
  ThreadWorkflowAttachmentHintedPayload as ContractsThreadWorkflowAttachmentHintedPayloadSchema,
  ThreadWorkflowArtifactsViewedPayload as ContractsThreadWorkflowArtifactsViewedPayloadSchema,
  ThreadWorkflowStaleResolvedPayload as ContractsThreadWorkflowStaleResolvedPayloadSchema,
  ThreadWorkflowSynchronizedPayload as ContractsThreadWorkflowSynchronizedPayloadSchema,
  ThreadWorkflowSpecificationDispatchedPayload as ContractsThreadWorkflowSpecificationDispatchedPayloadSchema,
  ThreadWorkflowSpecificationCheckpointedPayload as ContractsThreadWorkflowSpecificationCheckpointedPayloadSchema,
  ThreadWorkflowSpecificationCheckpointResolvedPayload as ContractsThreadWorkflowSpecificationCheckpointResolvedPayloadSchema,
  ThreadWorkflowSpecificationCompletedPayload as ContractsThreadWorkflowSpecificationCompletedPayloadSchema,
  ThreadWorkflowSpecificationFailedPayload as ContractsThreadWorkflowSpecificationFailedPayloadSchema,
  ThreadWorkflowTicketingDispatchedPayload as ContractsThreadWorkflowTicketingDispatchedPayloadSchema,
  ThreadWorkflowTicketingCheckpointedPayload as ContractsThreadWorkflowTicketingCheckpointedPayloadSchema,
  ThreadWorkflowTicketingCheckpointResolvedPayload as ContractsThreadWorkflowTicketingCheckpointResolvedPayloadSchema,
  ThreadWorkflowTicketBatchPublicationRequestedPayload as ContractsThreadWorkflowTicketBatchPublicationRequestedPayloadSchema,
  ThreadWorkflowTicketBatchPublicationUpdatedPayload as ContractsThreadWorkflowTicketBatchPublicationUpdatedPayloadSchema,
  ThreadWorkflowTicketingFailedPayload as ContractsThreadWorkflowTicketingFailedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
export const ThreadWayfinderPublicationUpdatedPayload =
  ContractsThreadWayfinderPublicationUpdatedPayloadSchema;
export const ThreadWayfinderMutationUpdatedPayload =
  ContractsThreadWayfinderMutationUpdatedPayloadSchema;
export const ThreadWayfinderReconciliationUpdatedPayload =
  ContractsThreadWayfinderReconciliationUpdatedPayloadSchema;
export const ThreadWayfinderResearchUpdatedPayload =
  ContractsThreadWayfinderResearchUpdatedPayloadSchema;
export const ThreadWorkflowAttachmentHintedPayload =
  ContractsThreadWorkflowAttachmentHintedPayloadSchema;
export const ThreadWorkflowAttachmentHintDismissedPayload =
  ContractsThreadWorkflowAttachmentHintDismissedPayloadSchema;
export const ThreadWorkflowAttachedPayload = ContractsThreadWorkflowAttachedPayloadSchema;
export const ThreadWorkflowRunPreflightedPayload =
  ContractsThreadWorkflowRunPreflightedPayloadSchema;
export const ThreadWorkflowRunConfirmedPayload = ContractsThreadWorkflowRunConfirmedPayloadSchema;
export const ThreadWorkflowSynchronizedPayload = ContractsThreadWorkflowSynchronizedPayloadSchema;
export const ThreadWorkflowArtifactsViewedPayload =
  ContractsThreadWorkflowArtifactsViewedPayloadSchema;
export const ThreadWorkflowArtifactAcknowledgedPayload =
  ContractsThreadWorkflowArtifactAcknowledgedPayloadSchema;
export const ThreadWorkflowStaleResolvedPayload = ContractsThreadWorkflowStaleResolvedPayloadSchema;
export const ThreadWorkflowSpecificationDispatchedPayload =
  ContractsThreadWorkflowSpecificationDispatchedPayloadSchema;
export const ThreadWorkflowSpecificationCheckpointedPayload =
  ContractsThreadWorkflowSpecificationCheckpointedPayloadSchema;
export const ThreadWorkflowSpecificationCheckpointResolvedPayload =
  ContractsThreadWorkflowSpecificationCheckpointResolvedPayloadSchema;
export const ThreadWorkflowSpecificationCompletedPayload =
  ContractsThreadWorkflowSpecificationCompletedPayloadSchema;
export const ThreadWorkflowSpecificationFailedPayload =
  ContractsThreadWorkflowSpecificationFailedPayloadSchema;
export const ThreadWorkflowTicketingDispatchedPayload =
  ContractsThreadWorkflowTicketingDispatchedPayloadSchema;
export const ThreadWorkflowTicketingCheckpointedPayload =
  ContractsThreadWorkflowTicketingCheckpointedPayloadSchema;
export const ThreadWorkflowTicketingCheckpointResolvedPayload =
  ContractsThreadWorkflowTicketingCheckpointResolvedPayloadSchema;
export const ThreadWorkflowTicketBatchPublicationRequestedPayload =
  ContractsThreadWorkflowTicketBatchPublicationRequestedPayloadSchema;
export const ThreadWorkflowTicketBatchPublicationUpdatedPayload =
  ContractsThreadWorkflowTicketBatchPublicationUpdatedPayloadSchema;
export const ThreadWorkflowTicketingFailedPayload =
  ContractsThreadWorkflowTicketingFailedPayloadSchema;
